### ISSUE TITLE
新手安装失败，编辑成功，求大神指点

### ISSUE THREAD

**Issue by 18158233082** [mokeyish/zerotier-edge#82]
D:\zerotier\zerotier-edge>pnpm install
Scope: all 2 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
webui prepare$ node prepare.mjs
│ node:internal/deps/undici/undici:13392
│       Error.captureStackTrace(err);
│             ^
│ TypeError: fetch failed
│     at node:internal/deps/undici/undici:13392:13
│     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
│     at async downloadRuleCompiler (file:///D:/zerotier/zerotier-edge/webui/prepare.mjs:164:65)
│     at async file:///D:/zerotier/zerotier-edge/webui/prepare.mjs:169:1 {
│   [cause]: Error: getaddrinfo ENOENT raw.githubusercontent.com
│       at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
│     errno: -4058,
│     code: 'ENOENT',
│     syscall: 'getaddrinfo',
│     hostname: 'raw.githubusercontent.com'
│   }
│ }
│ Node.js v23.0.0
│ Assertion failed: !(handle->flags & UV_HANDLE_CLOSING), file c:\ws\deps\uv\src\win\async.c, line 76
└─ Failed in 3.7s at D:\zerotier\zerotier-edge\webui
 ELIFECYCLE  Command failed with exit code 3221226505.

D:\zerotier\zerotier-edge>pnpm run build

> zerotier-edge@ build D:\zerotier\zerotier-edge
> npm run build-ui && cargo build --release
........
   Compiling axum v0.7.7
   Compiling zerotier-edge v0.1.6 (D:\zerotier\zerotier-edge)
warning: unused imports: `debug`, `error`, and `trace`
 --> src\log.rs:1:19
  |
1 | pub use tracing::{debug, error, info, trace, warn};
  |                   ^^^^^  ^^^^^        ^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `zerotier-edge` (bin "zerotier-edge") generated 1 warning (run `cargo fix --bin "zerotier-edge"` to apply 1 suggestion)
    Finished `release` profile [optimized] target(s) in 2m 15s

**Comment by mokeyish** [comment]
不是有直接下载的二进制程序么？

**Comment by 18158233082** [comment]
有的，用的挺好，就是有个小问题，删除结点删除不了，我想着是不是有新代码修复的，所以打算编译一下。

**Comment by mokeyish** [comment]
没有修复，有百分百重现的步骤么？有的话，我修复一下。只是偶现的，我也没多余时间研究。。。

我也就是偶尔用下。写个主要解决官方服务器宕机，所以设备无法连接问题。用自己的，自己可以保证在线。

**Comment by 18158233082** [comment]
可以重现的，我目前装在华为云 window server 2012 r2系统，配合zerotier 1.6.6（2012server只能装这个），发现这个问题，点击删除没反应，点后面隐藏是可以，再在隐藏列表里点删除就不隐藏了，😓

**Comment by mokeyish** [comment]
更新了一版，修复了配置覆盖问题，同时加了 actions 构建打包功能。你可以 fork 到你自己仓库，在 Actions 选择构建。
